site_name: Redbox
site_description: Bringing Generative AI to the way the Civil Service works
site_author: Incubator for AI
repo_url: https://github.com/i-dot-ai/redbox-copilot

theme:
  name: "material"
  palette:
    primary: "red"
    accent: "red"
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  

nav:
  - Home: index.md
  - Installation: DEVELOPER_SETUP.md
  - Architecture:
    - Overview: architecture/index.md
    - Workers and Queues: architecture/workers_and_queues.md
    - Transactions and Schema: architecture/transactions_and_schema.md
    - Docker and Dependencies: architecture/docker_and_dependencies.md
  - Code Reference: 
    - Home: code_reference/index.md
    - Models: 
      - Overview: code_reference/models/index.md
      - File: code_reference/models/file.md
      - Chunk: code_reference/models/chunk.md
      - Embedding: code_reference/models/embedding.md
      - Settings: code_reference/models/settings.md
    - Parsing:
      - Overview: code_reference/parsing/index.md
      - FileChunker: code_reference/parsing/file_chunker.md
      - Chunkers: code_reference/parsing/chunkers.md
      - Chunk Clustering: code_reference/parsing/chunk_clustering.md
    - Storage:
      - Overview: code_reference/storage/index.md
      - ElasticsearchStorageHandler: code_reference/storage/elasticsearch_storage_handler.md
  - Contributing: contributing.md

plugins:
    search: null
    mermaid2: null
    git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
    glightbox: null
    mkdocstrings:
      handlers:
        python:
          options:
            extensions:
            - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
            - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.pathconverter
  - codehilite:
      guess_lang: true
      use_pygments: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/i-dot-ai/redbox-copilot
    - icon: fontawesome/solid/envelope
      link: mailto:i-dot-ai-enquiries@cabinetoffice.gov.uk

        