[tool.poetry]
name = "redbox"
version = "0.1.0"
description = ""
authors = ["i.AI <i-dot-ai-team@cabinetoffice.gov.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pydantic = "^2.6.3"
elasticsearch = "^8.12.0"
requests = "^2.31.0"
langchain = "^0.1.9"
tiktoken = "^0.6.0"
boto3 = "^1.34.53"
pika = "^1.3.2"
pydantic-settings = "^2.2.1"

[tool.poetry.group.api.dependencies]
fastapi = "^0.110.0"
python-multipart = "^0.0.9"
uvicorn = "^0.27.1"


[tool.poetry.group.worker.dependencies]
pika = "^1.3.2"

[tool.poetry.group.embed.dependencies]
sentence-transformers = "^2.5.0"

[tool.poetry.group.ingest.dependencies]
unstructured = {version = "^0.12.5", extras = ["all-docs"]}
opencv-python-headless = "^4.9.0.80"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
pylint = "^3.1.0"
mypy = "^1.8.0"
types-python-dateutil = "^2.8.19.20240106"
types-markdown = "^3.5.0.20240129"
pytest-cov = "^4.1.0"
ruff = "^0.3.0"
python-dotenv = "^1.0.1"
jupyter = "^1.0.0"
ipykernel = "^6.29.3"
pre-commit = "^3.6.2"
boto3-stubs = "^1.34.53"


[tool.poetry.group.streamlit-app.dependencies]
streamlit = "^1.31.1"
lxml = "^5.1.0"
loguru = "^0.7.2"


[tool.poetry.group.ai.dependencies]
anthropic = "^0.16.0"
litellm = "^1.28.1"
openai = "^1.13.3"
langchain-community = "^0.0.24"


[tool.poetry.group.streamlitapp.dependencies]
cognitojwt = "^1.4.1"
pandas = "^2.2.1"
html2markdown = "^0.1.7"
streamlit-feedback = "^0.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
download-model = 'download_embedder:download'
