[tool.ruff]
line-length = 120
target-version = 'py311'

[tool.poetry]
name = "redbox"
version = "1.0.0"
description = ""
authors = ["i.AI <i-dot-ai-enquiries@cabinetoffice.gov.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pydantic = "^2.6.4"
elasticsearch = "^8.12.0"
requests = "^2.31.0"
langchain = "^0.1.11"
tiktoken = "^0.6.0"
boto3 = "^1.34.65"
pika = "^1.3.2"
pydantic-settings = "^2.2.1"
bumpversion = "^0.6.0"

[tool.poetry.group.api.dependencies]
fastapi = "^0.110.0"
python-multipart = "^0.0.9"
uvicorn = "^0.28.0"
sentence-transformers = "^2.5.1"

[tool.poetry.group.worker.dependencies]
pika = "^1.3.2"

[tool.poetry.group.ingest.dependencies]
unstructured = {version = "^0.12.5", extras = ["all-docs"]}
opencv-python-headless = "^4.9.0.80"
sentence-transformers = "^2.5.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-env = "^1.1.1"
pytest-mock = "^3.12.0"
pytest-cov = "^4.1.0"
pylint = "^3.0.3"
mypy = "^1.9.0"
types-python-dateutil = "^2.9.0.20240315"
types-markdown = "^3.6.0.20240316"
ruff = "^0.3.3"
python-dotenv = "^1.0.1"
jupyter = "^1.0.0"
ipykernel = "^6.29.2"
pre-commit = "^3.6.2"
freezegun = "^1.2.2"
pep8-naming = "^0.13.3"
bandit = "^1.7.8"
django-types = "^0.19.1"
types-python-jose = "^3.3.4.8"
detect-secrets = "^1.4.0"
types-pytz = "^2024.1.0.20240203"
boto3-stubs = "^1.34.65"


[tool.poetry.group.streamlit-app.dependencies]
streamlit = "^1.32.2"
lxml = "^5.1.0"
loguru = "^0.7.2"
streamlit-feedback = "^0.1.3"
html2markdown = "^0.1.7"

[tool.poetry.group.ai.dependencies]
anthropic = "^0.20.0"
litellm = "^1.32.1"
openai = "^1.14.1"


[tool.poetry.group.django-app.dependencies]
python = "^3.11.2"
django = "^4.2.8"
django-compressor = "^4.4"
django-libsass = "^0.9"
whitenoise = "^6.6.0"
watchdog = {extras = ["watchmedo"], version = "^3.0.0"}
jinja2 = "^3.1.2"
django-environ = "^0.11.2"
django-use-email-as-username = "^1.4.0"
markdown-it-py = "^3.0.0"
waitress = "^2.1.2"
psycopg2-binary = "^2.9.9"
pyyaml = "^6.0.1"
pytz = "^2024.1"
django-permissions-policy = "^4.18.0"
django-csp = "^3.7"
django-single-session = "^0.2.0"
sentry-sdk = "^1.34.0"
django-storages = "^1.14.2"
django-health-check = "<3.19.0" # this pin can be removed once https://github.com/revsys/django-health-check/issues/412 is resolved
boto3 = "^1.34.65"
urllib3 = "<2.3"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
requests = "^2.31.0"
presidio-analyzer = "^2.2.351"
en_core_web_sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz"}
defusedcsv = "^2.0.0"
python-dotenv = "^1.0.0"
furl = "^2.1.3"
django-allauth = "^0.61.1"
django-otp = "^1.3.0"
humanize = "^4.9.0"

[tool.poetry.group.pytest-django.dependencies]
pytest-django = "^4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
download-model = 'download_embedder:download'
