name: Django

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    paths:
      - django_app/**
      - Makefile
      - .github/**
    branches:
      - 'main'
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'dependabot/**'
      - 'security/**'
  workflow_dispatch:


jobs:

  check_migrations:
    name: Check migrations

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v3

      - name: Copy env file
        run: |
          cp .env.test .env

      - name: Run migrations
        run: |
          make check-migrations
