name: Django

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    paths:
      - django_app/**
      - Makefile
      - .github/**
    branches:
      - 'main'
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'dependabot/**'
  workflow_dispatch:


jobs:

  check_migrations:
    name: Check migrations

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v3

      - name: Copy env file
        run: |
          cp .env.django .env

      - name: Run migrations
        run: |
          make check-migrations

  run_tests:
    name: Run tests

    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v3

    - name: Copy env file
      run: |
        cp .env.django .env

    - name: Run tests
      run: |
        make test-django
