# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Integration Tests

on:
  # weekday mealtimes
  schedule:
    - cron: '0 6,12,18 * * 1-5'
  # or on-demand
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.7.0

    - name: Build Containers
      run: |
        mkdir -p data/elastic/
        chmod -R 777 data/
        cp .env.integration .env
#        docker compose up -d --wait core-api embedder ingester

    - name: Wait 60s for services to be ready
      run: |
        sleep 60

    - name: Test integration with pytest
      run: |
        pip install requests
        pip install pytest
        python -m pytest tests

    - name: notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      if: ${{ failure() }}
      with:
        channel-id: 'C05D67P6M34'
        payload: |
          {
            "text": "Integration Tests Failed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":fire: Integration Tests are failing :fire_engine:"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "logs"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK